GET http://localhost:4000/user-api/users

### post request
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "username":"jkss",
    "password":"mypass123",
    "age":19,
}