### Create new product req

POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "productName":"Trimmer",
    "price":4000,
    "brand":"panasonic"
}

### Getting all the products
GET http://localhost:4000/product-api/products

### Create user req
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "name":"jitu",
    "email":"jitu@gmail.com",
    "password":"jitu",
    "cart":[]
}

### REq to add product to cart
# PUT http://localhost:4000/user-api/user-cart/userid/<userid>/productid/<productid>
PUT http://localhost:4000/user-api/user-cart/userid/698071abf81b05f222f28bd4/productid/6980679330d9afbd06ab8d8d